@startuml

skinparam classAttributeIconSize 0

interface Component

class BackgroundComponent {
    - y1: float
    - y2: float
    - speed: int
    + BackgroundComponent(y1: float, y2: float, speed: int)
}

class BoundsCircleComponent {
    - bounds: Circle
    + BoundsCircleComponent(radius: int)
}

class BoundsRectangleComponent {
    - bounds: Rectangle
    + BoundsRectangleComponent(width: int, height: int)
}

class CollisionComponent {
    - collidedEntity: Entity
    - hit: boolean
    + reset()
}

class FuelComponent {
    - fuelLevel: int
    - maxFuelLevel: int
    + FuelComponent(fuelLevel: int)
}

class PositionComponent {
    - x: float
    - y: float
    + PositionComponent(x: float, y: float)
    + updateX(x: float): void
    + printPosition(): void
}

class ScoreComponent {
    - score: int
    - gameOver: boolean
    + ScoreComponent(score: int)
    + getScore(): int
}

enum SpecificTypeComponent {
    BIRD
    PLANE
    ASTEROID
    SATELLITE
    FUELCAN
}

class SpriteComponent {
    - sprite: Sprite
    - texture: Texture
    + SpriteComponent(texture: Texture)
}

enum TypeComponent {
    OBSTACLE
    POWERUP
    ROCKET
}

class VelocityComponent {
    - x: float
    - y: float
    - speedSet: boolean
    + VelocityComponent()
    + setSpeed(x: float, y: float): void
    + isSpeedSet(): boolean
}

Component <|-- BackgroundComponent
Component <|-- BoundsCircleComponent
Component <|-- BoundsRectangleComponent
Component <|-- CollisionComponent
Component <|-- FuelComponent
Component <|-- PositionComponent
Component <|-- ScoreComponent
Component <|-- SpriteComponent
Component <|-- VelocityComponent
Component <|-- SpecificTypeComponent
Component <|-- TypeComponent

@enduml